project:
  type: book

book:
  title: "CFDE Metrics Handbook"
  date: "last-modified"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Metrics"
      chapters:
        - online_user.qmd
        - infrastructure_costs.qmd
        - technical_performance.qmd
    - part: "DCC Metrics"
    - part: "Center Metrics"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
